config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:index, :new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title,  presence: true, uniqueness: true
  validates :overview, presence: true
end

# validates :name, :address, :category, presence: true
# validates :category, inclusion: { in: %w(chinese italian japanese french belgian),
#   message: "%{value} is not a valid category" }

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  # :index, :new, :create

  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @lists = List.all
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>
<% @bookmarks.each do |bookmark| %>
  <ul>
    <li><%= bookmark.comment %></li>
  </ul>
<% end %>

app/views/bookmarks/new.html.erb
<h3>Add a movie to your <%= @list.name %> list</h3>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
  <%= f.association :movie, prompt: 'Select a movie' %>
  <%= f.submit%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies Watch List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner">
  <h1>Movies lists</h1>
</div>

<ul>
  <% @lists.each do |list| %>
    <li > <%= link_to list.name, list_path(list) %></li>
  <% end %>
  <li class="add-list">
  <%= link_to 'add list', new_list_path %>
  </li>
</ul>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit%>
<% end %>

app/views/lists/show.html.erb
<div class="container">
<h1> <%= @list.name %></h1>

<br>

<h3>Movies:</h3>
<p><% @list.movies.each do |movie| %></p>
  <p>Title: <%= movie.title %></p>
  <p>Rating: <%= movie.rating %></p>
  <p><%= movie.overview %></p>
<% end %>

<p><% @list.bookmarks.each do |bookmark| %></p>
  <p><%= bookmark.comment %></p>
<% end %>


<p><%= link_to "Add a movie to this list", new_list_bookmark_path(@list) %></p>
<p><%= link_to "Back to List", lists_path %></p>